<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OptiDiag.I2c.Abstractions\OptiDiag.I2c.Abstractions.csproj" />
    <ProjectReference Include="..\OptiDiag.Protocols.Abstractions\OptiDiag.Protocols.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
